package encrypt;

public enum MODULEETYPE {
	QQ, QQ_2, QQ_MODULE, QQ_2_MODULE, Q_PLUS_DIR, QQ_MODULE_TEST, TEST, WECHAT, PLUGIN, PUBLIC_FOLDER, ROBOT, MIAO, CRACK_SIGN, OTHER, TEST_OTHER_ROBOT, TEST_OTHER_ROBOT_PLUGIN

}